basic_settings:
  site_title: Kyle Card
  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/logo.png
  mobile_logo_image: /assets/img/logo.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'About me'
      url: /about
    - title: 'Research'
      url: /research
    - title: 'Publications'
      url: /publications
    - title: 'Blog'
      url: /blog
    - title: 'CV'
      url: https://drive.google.com/file/d/1ICrh-7lJv9rmnkejKHVsfZb9Y7_jTG5c/view?usp=sharing
      target: '_blank'
    - title: 'Contact'
      url: /contact

footer_settings:
  footer_tagline:

contact_settings:
  form_action: 'https://formspree.io/f/xdoyqgev'
  confirmation_url: '/thanks/'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  twitter_url: 'https://twitter.com/kylejcard'
  scholar_url: 'https://scholar.google.com/citations?user=vxKQDvgAAAAJ&hl=en'
  github_url: 'https://github.com/kylecard'
  linkedin_url: 'https://www.linkedin.com/in/kylecard'

#authors:
#  tom:
#    name: Tom
#    picture: /assets/img/faces/team-1.jpg

advanced_settings:
  google_analytics: 'G-W72422Y3K4'
  header_js: 
  footer_js: 